version: '3.8'

services:
  posgres-db:
    image: postgres:17.2-alpine
    mem_limit: 512m
    ports:
      - "5454:5432"
    environment:
      POSTGRES_PASSWORD: developer
    volumes:
      - ./init-sql:/docker-entrypoint-initdb.d
    networks:
      default: {}

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: developer
      MONGO_INITDB_ROOT_PASSWORD: developer
    volumes:
      - mongodb_data:/data/db

networks:
  default:
    driver: bridge

volumes:
  posgres-db:
    driver: "local"
  mongodb_data:
    driver: "local"