version: '2'

services:
  posgres-db:
    image: postgres:17.2-alpine
    mem_limit: 512m
    ports:
      - "5454:5432"
    environment:
      POSTGRES_PASSWORD: developer
    volumes:
      - ./init-sql:/docker-entrypoint-initdb.d
    networks:
      default: {}

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_LISTENERS: >
        INSIDE://0.0.0.0:9092,
        OUTSIDE://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: >
        INSIDE://kafka:9092,
        OUTSIDE://localhost:29092

    depends_on:
      - zookeeper
    networks:
      - default

  connect:
    image: confluentinc/cp-kafka-connect:7.4.0
    ports:
      - "8083:8083"
    depends_on:
      - kafka
    environment:
      CONNECT_BOOTSTRAP_SERVERS: kafka:9092
      CONNECT_REST_PORT: 8083
      CONNECT_REST_ADVERTISED_HOST_NAME: "localhost"
      CONNECT_REST_ADVERTISED_PORT: "8083"
      CONNECT_GROUP_ID: "connect-cluster"

      CONNECT_CONFIG_STORAGE_TOPIC: connect-configs
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: "1"
      CONNECT_OFFSET_STORAGE_TOPIC: connect-offsets
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: "1"
      CONNECT_STATUS_STORAGE_TOPIC: connect-status
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: "1"

      CONNECT_KEY_CONVERTER: org.apache.kafka.connect.storage.StringConverter
      CONNECT_VALUE_CONVERTER: org.apache.kafka.connect.storage.StringConverter
      CONNECT_INTERNAL_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_INTERNAL_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter

      CONNECT_PLUGIN_PATH: /usr/share/java,/usr/share/java/kafka-connect-jdbc

    volumes:
      - ./data:/data
      - ./plugins/kafka-connect-jdbc:/usr/share/java/kafka-connect-jdbc

    networks:
      - default


networks:
  default:
    driver: bridge

volumes:
  posgres-db:
    driver: "local"
